from enum import Enum


class DotEnvEnum(Enum):
    USER_ADM = "USER_ADM"
    USER_ADM_PASSWORD = "USER_ADM_PASSWORD"
    DATABASE_URI = "DATABASE_URI"
    IP_APPLICATION = "IP_APPLICATION"
    PORT_APPLICATION = "PORT_APPLICATION"
