name: Run Unit Test via Pytest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
  
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with Ruff
        run: |
          pip install ruff
          ruff --format=github --target-version=py310 .
        continue-on-error: true
      - name: Create env file
        run: |
          touch .env
          echo DATABASE_URI=${{ vars.DATABASE_URI }} >> .env
          echo USER_ADM=${{ vars.USER_ADM }} >> .env
          echo USER_ADM_PASSWORD=${{ vars.USER_ADM_PASSWORD }} >> .env
          cat .env
      - name: Test with pytest
        run: |
          coverage run -m pytest -v -s --cov-config=.coveragerc
      - name: Generate Coverage Report
        run: |
          coverage report -m
