name: Run Unit Test via Pytest
on: push
env:
  ENV_TEST: ${{ vars.ENV_TEST }}
  DATABASE_URI: ${{ vars.DATABASE_URI }}
  USER_ADM: ${{ vars.USER_ADM }}
  USER_ADM_PASSWORD: ${{ vars.USER_ADM_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
  
    steps:
      - name: Print env_test
        run: echo "Hello ENV_TEST"

      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with Ruff
        run: |
          pip install ruff
          ruff --format=github --target-version=py310 .
        continue-on-error: true
      - name: Test with pytest
        run: |
          coverage run -m pytest -v -s --cov-config=.coveragerc
      - name: Generate Coverage Report
        run: |
          coverage report -m
